services:
  web:
    build: .
    ports:
    # APP_PORT : CONTAINER_PORT
      - "${APP_PORT}${PORT}"
    environment:
      - PORT={$PORT}
      - DATABASE_URL=$DATABASE_URL
    command: ["/app/server.exe", "-PORT=${PORT}"]


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:18
    ports: 
      - "5432:5432" 
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=url_map_db
    volumes:
      - "db_data:/var/lib/postgresql"
  
volumes:
  db_data: